### ISSUE TITLE
train_cascade.py slow speed

### ISSUE THREAD

**Issue by Rmsharks4** [SenticNet/CASCADE#2]
Its been like 6 hours and its only gotten uptill 20 - its too slow no?
(python 3.64, Windows 10, tensorflow 1.36)

**Comment by devamanyu** [comment]
Hi, 

train_cascade.py uses standard CNN code calling tensorflow api layers. 
Presently, we have set a smaller batch_size. You might try with a larger batch_size to increase the speed conditioned on your availability to appropriate GPU hardware.

Thanks!
